// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/alchemy-furnace/server/internal/service/agent_service"
	"github.com/alchemy-furnace/server/internal/service/chat_service"
	"github.com/alchemy-furnace/server/internal/service/credential"
	"github.com/alchemy-furnace/server/internal/service/distillation_service"
	"github.com/alchemy-furnace/server/internal/service/fusion_service"
	"github.com/alchemy-furnace/server/internal/service/language_pattern_service"
	"github.com/alchemy-furnace/server/internal/service/model_service"
	"github.com/alchemy-furnace/server/internal/service/pill_service"
	"github.com/alchemy-furnace/server/internal/service/provider_service"
	"github.com/alchemy-furnace/server/internal/service/trial_service"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/agent"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/chat"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/distillation"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/fusion"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/model"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/pill"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/trial"
	"github.com/alchemy-furnace/server/server/http/service"
)

// Injectors from wire.go:

// NewPill 金丹处理器装配
func NewPill() *pill.Pill {
	daoPill := service.ProvidePillDao()
	pill_servicePill := pill_service.New(daoPill)
	pillPill := pill.New(pill_servicePill)
	return pillPill
}

// NewAgent 道人处理器装配
func NewAgent() *agent.Agent {
	daoAgent := service.ProvideAgentDao()
	daoPill := service.ProvidePillDao()
	model := service.ProvideModelDao()
	agent_serviceAgent := agent_service.New(daoAgent, daoPill, model)
	memory := service.ProvideMemoryDao()
	modelResolver := credential.NewResolver()
	provider := service.NewEngineBaseURL()
	serviceMemory := service.ProvideMemoryService(memory, modelResolver, provider)
	agentAgent := agent.New(agent_serviceAgent, serviceMemory)
	return agentAgent
}

// NewTrial 试丹处理器装配
func NewTrial() *trial.Trial {
	daoPill := service.ProvidePillDao()
	client := service.NewSynthesisClient()
	modelResolver := credential.NewResolver()
	trial_serviceTrial := trial_service.New(daoPill, client, modelResolver)
	trialTrial := trial.New(trial_serviceTrial)
	return trialTrial
}

// NewFusion 金丹融合处理器装配
func NewFusion() *fusion.Fusion {
	daoPill := service.ProvidePillDao()
	fusionClient := service.NewFusionClient()
	modelResolver := credential.NewResolver()
	fusion_serviceFusion := fusion_service.New(daoPill, fusionClient, modelResolver)
	fusionFusion := fusion.New(fusion_serviceFusion)
	return fusionFusion
}

func NewDistillation() *distillation.Handler {
	client := service.NewDistillationClient()
	modelResolver := credential.NewResolver()
	daoPill := service.ProvidePillDao()
	distillation_serviceService := distillation_service.New(client, modelResolver, daoPill)
	handler := distillation.New(distillation_serviceService)
	return handler
}

// NewModel 供应商与模型管理处理器装配
func NewModel() *model.Model {
	provider := service.ProvideProviderDao()
	daoModel := service.ProvideModelDao()
	providerService := provider_service.New(provider, daoModel)
	modelService := model_service.New(daoModel, provider)
	modelModel := model.New(providerService, modelService)
	return modelModel
}

// NewChat 对话处理器装配
func NewChat() *chat.Chat {
	daoChat := service.ProvideChatDao()
	daoAgent := service.ProvideAgentDao()
	client := service.NewSynthesisClient()
	modelResolver := credential.NewResolver()
	languagePatternService := language_pattern_service.New(daoAgent, client, modelResolver)
	provider := service.NewEngineBaseURL()
	memory := service.ProvideMemoryDao()
	serviceMemory := service.ProvideMemoryService(memory, modelResolver, provider)
	chat_serviceChat := chat_service.NewDynamic(daoChat, daoAgent, languagePatternService, modelResolver, provider, serviceMemory)
	chatChat := chat.New(chat_serviceChat)
	return chatChat
}
