// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/user"
	"github.com/alchemy-furnace/server/server/http/service"
)

// NewUser 用户档案处理器装配
func NewUser() *user.User {
	db := service.ProvideDB()
	userUser := user.New(db)
	return userUser
}
