// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/alchemy-furnace/server/internal/dao"
	"github.com/alchemy-furnace/server/internal/service/agent_service"
	"github.com/alchemy-furnace/server/internal/service/chat_service"
	"github.com/alchemy-furnace/server/internal/service/credential"
	"github.com/alchemy-furnace/server/internal/service/language_pattern_service"
	"github.com/alchemy-furnace/server/internal/service/model_service"
	"github.com/alchemy-furnace/server/internal/service/pill_service"
	"github.com/alchemy-furnace/server/internal/service/provider_service"
	"github.com/alchemy-furnace/server/internal/service/trial_service"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/agent"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/chat"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/model"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/pill"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/trial"
	"github.com/alchemy-furnace/server/server/http/service"
)

// Injectors from wire.go:

// NewPill 金丹处理器装配
func NewPill() *pill.Pill {
	pillDao := dao.NewPillDao()
	pill_servicePill := pill_service.New(pillDao)
	pillPill := pill.New(pill_servicePill)
	return pillPill
}

// NewAgent 道人处理器装配
func NewAgent() *agent.Agent {
	agentDao := dao.NewAgentDao()
	pillDao := dao.NewPillDao()
	modelDao := dao.NewModelDao()
	agent_serviceAgent := agent_service.New(agentDao, pillDao, modelDao)
	agentAgent := agent.New(agent_serviceAgent)
	return agentAgent
}

// NewTrial 试丹处理器装配
func NewTrial() *trial.Trial {
	pillDao := dao.NewPillDao()
	synthesisClient := service.NewSynthesisClient()
	modelResolver := credential.NewResolver()
	trialService := trial_service.New(pillDao, synthesisClient, modelResolver)
	trialTrial := trial.New(trialService)
	return trialTrial
}

// NewModel 供应商与模型管理处理器装配
func NewModel() *model.Model {
	providerDao := dao.NewProviderDao()
	modelDao := dao.NewModelDao()
	providerService := provider_service.New(providerDao, modelDao)
	modelService := model_service.New(modelDao, providerDao)
	modelModel := model.New(providerService, modelService)
	return modelModel
}

// NewChat 对话处理器装配
func NewChat() *chat.Chat {
	chatDao := dao.NewChatDao()
	agentDao := dao.NewAgentDao()
	synthesisClient := service.NewSynthesisClient()
	modelResolver := credential.NewResolver()
	engineBaseURL := service.NewEngineBaseURL()
	languagePatternService := language_pattern_service.New(agentDao, synthesisClient, modelResolver)
	chatService := chat_service.New(chatDao, agentDao, languagePatternService, modelResolver, engineBaseURL)
	chatChat := chat.New(chatService)
	return chatChat
}
