// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/alchemy-furnace/server/internal/dao"
	"github.com/alchemy-furnace/server/internal/service/agent_service"
	"github.com/alchemy-furnace/server/internal/service/pill_service"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/agent"
	"github.com/alchemy-furnace/server/server/http/gateway/web/handler/pill"
)

// Injectors from wire.go:

// NewPill 金丹处理器装配
func NewPill() *pill.Pill {
	pillDao := dao.NewPillDao()
	pill_servicePill := pill_service.New(pillDao)
	pillPill := pill.New(pill_servicePill)
	return pillPill
}

// NewAgent 道人处理器装配
func NewAgent() *agent.Agent {
	agentDao := dao.NewAgentDao()
	pillDao := dao.NewPillDao()
	modelDao := dao.NewModelDao()
	agent_serviceAgent := agent_service.New(agentDao, pillDao, modelDao)
	agentAgent := agent.New(agent_serviceAgent)
	return agentAgent
}
